- name: Install Android SDK and accept licenses
  run: |
    mkdir -p $HOME/android-sdk/cmdline-tools
    wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
    unzip cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
    rm cmdline-tools.zip
    yes | $HOME/android-sdk/cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses
    yes | $HOME/android-sdk/cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-33" "build-tools;36.1.0"
